# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Boolean.xdc

# Block Designs: bd/uart_led_design/uart_led_design.bd
# Block Designs: The module: 'uart_led_design' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/uart_led_design/ip/uart_led_design_axi_uartlite_0_0/uart_led_design_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_led_design_axi_uartlite_0_0 || ORIG_REF_NAME==uart_led_design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/uart_led_design/ip/uart_led_design_axi_uartlite_1_0/uart_led_design_axi_uartlite_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_led_design_axi_uartlite_1_0 || ORIG_REF_NAME==uart_led_design_axi_uartlite_1_0} -quiet] -quiet

# IP: bd/uart_led_design/ip/uart_led_design_tx_ctrl_0_0/uart_led_design_tx_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_led_design_tx_ctrl_0_0 || ORIG_REF_NAME==uart_led_design_tx_ctrl_0_0} -quiet] -quiet

# IP: bd/uart_led_design/ip/uart_led_design_rx_ctrl_0_0/uart_led_design_rx_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_led_design_rx_ctrl_0_0 || ORIG_REF_NAME==uart_led_design_rx_ctrl_0_0} -quiet] -quiet

# IP: bd/uart_led_design/ip/uart_led_design_rst_inv_0_0/uart_led_design_rst_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_led_design_rst_inv_0_0 || ORIG_REF_NAME==uart_led_design_rst_inv_0_0} -quiet] -quiet

# IP: bd/uart_led_design/ip/uart_led_design_clk_wiz_0_0/uart_led_design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_led_design_clk_wiz_0_0 || ORIG_REF_NAME==uart_led_design_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/uart_led_design/uart_led_design_ooc.xdc
