# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/NexysA7.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_inv_0_0/system_rst_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_inv_0_0 || ORIG_REF_NAME==system_rst_inv_0_0} -quiet] -quiet

# IP: bd/system/ip/system_blk_mem_gen_0_1/system_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_blk_mem_gen_0_1 || ORIG_REF_NAME==system_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/system/ip/system_blk_mem_gen_0_2/system_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_blk_mem_gen_0_2 || ORIG_REF_NAME==system_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_core_0_0/system_core_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_core_0_0 || ORIG_REF_NAME==system_core_0_0} -quiet] -quiet

# IP: bd/system/ip/system_memory_select_0_0/system_memory_select_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_memory_select_0_0 || ORIG_REF_NAME==system_memory_select_0_0} -quiet] -quiet

# IP: bd/system/ip/system_controller_system_0_0/system_controller_system_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_controller_system_0_0 || ORIG_REF_NAME==system_controller_system_0_0} -quiet] -quiet

# XDC: w:/dsd-project/ProcessorSystem/ProcessorSystem.gen/sources_1/bd/system/system_ooc.xdc
